# Unit Tests for tf-molecule-kms-key-alias-aws
#
# These tests use a mock AWS provider — no real AWS calls are made (plan-only).
# Run with:        terraform test
# Run verbose:     terraform test -verbose
# Run specific:    terraform test -run "creates_when_enabled"

mock_provider "aws" {}

# tf-label labels applied to every run in this file.
variables {
  namespace = "eg"
  stage     = "test"
  name      = "thing"

  description         = "Unit-test KMS key"
  enable_key_rotation = true
}

# ---------------------------------------------------------------------------
# Test: Module creates the KMS key + alias when enabled (default)
# ---------------------------------------------------------------------------
run "creates_when_enabled" {
  command = plan

  # output.enabled is derived from module.this.enabled and is known at plan
  # time. The key_id / alias ARNs are generated by the (mock) provider and are
  # only known after apply, so they cannot be asserted in a plan-only run.
  assert {
    condition     = output.enabled == true
    error_message = "enabled output should be true when the module is enabled"
  }
}

# ---------------------------------------------------------------------------
# Test: enabled flag propagates to the enabled output
# ---------------------------------------------------------------------------
# NOTE: A full `enabled = false` plan cannot be exercised here. When disabled,
# the key atom outputs a null key_id, which is passed as target_key_id into the
# alias atom; that atom has a non-null variable validation
# (`length(var.target_key_id) > 0`) which errors at plan time on a null value.
# We therefore assert the enabled flag propagation using a static label input.
run "enabled_flag_propagates" {
  command = plan

  variables {
    label_order = ["namespace", "stage", "name"]
  }

  assert {
    condition     = output.enabled == true
    error_message = "enabled output should reflect module.this.enabled (true by default)"
  }
}
